version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app_db
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432"
    networks:
      - task
  migrate:
    image: migrate/migrate
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    profiles:
      - donotstart
    networks:
      - task
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - task
  app:
    build:
      context: ./docker/dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./.go/pkg:/go/pkg
      - ./.go-cache:/go-cache
      - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
    working_dir: /app
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      GOCACHE: /go-cache
    networks:
      - task
    depends_on:
      - db
      - redis


volumes:
  redis_data:
networks:
  task:
    driver: bridge
